[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "diabetes-readmission-ml-pipeline"
version = "0.1.0"
description = "Interpretable machine learning pipeline for 30-day hospital readmission in patients with diabetes."
readme = "README.md"
requires-python = ">=3.11,<3.12"
license = "MIT"
authors = [
    { name = "Joan Carreras Díaz" }
]
dependencies = [
    "numpy>=1.26,<3",
    "pandas>=2.2,<4",
    "scikit-learn>=1.5,<2",
    "matplotlib>=3.8,<4",
    "ucimlrepo>=0.0.7"
]

[project.optional-dependencies]
dev = [
    "jupyterlab>=4",
    "ipykernel>=6",
    "pytest>=8"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools]
package-dir = {"" = "src"}
